import { useEffect, useMemo, useRef, useState } from 'react'
const noms=['Do','Do♯','Ré','Ré♯','Mi','Fa','Fa♯','Sol','Sol♯','La','La♯','Si'], naturelles=['Do','Ré','Mi','Fa','Sol','La','Si'], couleurs=['#ef4b4b','#ef4b4b','#f28c28','#f28c28','#f4d43d','#70d35b','#70d35b','#35cbbb','#35cbbb','#6876e8','#6876e8','#d94fc3']
const noires=new Set([1,3,6,8,10]), alea=<T,>(l:T[])=>l[Math.floor(Math.random()*l.length)]
function CorrespondanceCouleurs(){const naturellesMidi=[60,62,64,65,67,69,71];return <details className="color-reference"><summary>Repère couleurs ↔ notes</summary><div>{naturellesMidi.map(m=><span key={m}><i style={{background:couleurs[m%12]}}/><b>{noms[m%12]}</b></span>)}</div><small>Une croix sur le carré indique un dièse.</small></details>}
function Carte({midi,reveler,afficherDiese=false,jauge,annonce}:{midi:number;reveler:boolean;afficherDiese?:boolean;jauge?:{duree:number;cle:number}|null;annonce?:number|null}){const libelle=afficherDiese?noms[midi%12].replace('♯','#'):noms[midi%12].replace('♯','');return <div className="flash-stage"><div className="flash-visual"><div className="flash-note" style={{background:couleurs[midi%12]}}>{noires.has(midi%12)&&<b>×</b>}</div>{jauge!==undefined&&<div className="time-gauge" aria-hidden="true">{jauge&&!annonce&&<i key={jauge.cle} style={{animationDuration:jauge.duree+'s'}}/>}</div>}</div><div className="flash-answer">{annonce?<div className="level-inline">⚡ {annonce===15?'MAX':'N'+annonce}</div>:<strong className={reveler?'visible':''}>{libelle}</strong>}</div></div>}
export function Practice(){
 const [experience,setExperience]=useState<'serie'|'long'>('serie'),[mode,setMode]=useState<'actif'|'passif'>('actif'),[actif,setActif]=useState(false),[reveler,setReveler]=useState(false),[midi,setMidi]=useState(60),[compteur,setCompteur]=useState(0),[reponse,setReponse]=useState('')
 const [delai,setDelai]=useState(2),[duree,setDuree]=useState(60),[chromatique,setChromatique]=useState(true),[score,setScore]=useState(0),[vies,setVies]=useState(3),[record,setRecord]=useState(()=>Number(localStorage.getItem('practice-long-run-record')||0)),[delaiCourant,setDelaiCourant]=useState(3),[niveau,setNiveau]=useState(1),[annonceNiveau,setAnnonceNiveau]=useState<number|null>(null),[partieFinie,setPartieFinie]=useState(false)
 const fin=useRef(0),debut=useRef(0),precedente=useRef<number|null>(null),reponseRef=useRef(''),viesRef=useRef(3),scoreRef=useRef(0),niveauRef=useRef(1)
 const longRun=experience==='long', notes=useMemo(()=>Array.from({length:12},(_,i)=>60+i).filter(m=>longRun||chromatique||!noires.has(m%12)),[chromatique,longRun])
 useEffect(()=>{if(!actif)return;let a=0,b=0;const lancer=()=>{if(!longRun&&Date.now()>=fin.current){setActif(false);setReveler(false);return}const palier=longRun?Math.min(14,Math.floor((Date.now()-debut.current)/30000)):0,prochainNiveau=palier+1;if(longRun&&prochainNiveau!==niveauRef.current){niveauRef.current=prochainNiveau;setNiveau(prochainNiveau);setDelaiCourant(Math.max(.2,3-palier*.2));setReveler(false);setAnnonceNiveau(prochainNiveau);b=window.setTimeout(()=>{setAnnonceNiveau(null);lancer()},1200);return}const candidates=notes.filter(n=>precedente.current===null||noms[n%12].replace('♯','')!==noms[precedente.current%12].replace('♯','')),suivante=alea(candidates),attente=longRun?Math.max(.2,3-palier*.2):delai;precedente.current=suivante;reponseRef.current='';setMidi(suivante);setDelaiCourant(attente);setReveler(false);setReponse('');setCompteur(c=>c+1);a=window.setTimeout(()=>{setReveler(true);if(longRun){const juste=reponseRef.current===noms[suivante%12].replace('♯','');if(juste){scoreRef.current+=1;setScore(scoreRef.current);if(scoreRef.current>record){setRecord(scoreRef.current);localStorage.setItem('practice-long-run-record',String(scoreRef.current))}}else{viesRef.current-=1;setVies(viesRef.current);if(viesRef.current===0){b=window.setTimeout(()=>{setActif(false);setPartieFinie(true)},900);return}}}b=window.setTimeout(lancer,900)},attente*1000)};lancer();return()=>{clearTimeout(a);clearTimeout(b)}},[actif,delai,longRun,notes])
 function demarrer(){precedente.current=null;reponseRef.current='';setCompteur(0);setReveler(false);setPartieFinie(false);if(longRun){debut.current=Date.now();scoreRef.current=0;viesRef.current=3;setScore(0);setVies(3);setDelaiCourant(3);setNiveau(1);niveauRef.current=0;setAnnonceNiveau(null)}else fin.current=Date.now()+duree*1000;setActif(true)}
 function choisir(n:string){if(longRun&&reponseRef.current)return;reponseRef.current=n;setReponse(n)}
 function changerExperience(e:'serie'|'long'){setExperience(e);setPartieFinie(false);setReveler(false);setReponse('')}
 const interactif=longRun||mode==='actif', juste=reponse===noms[midi%12].replace('♯','')
 return <section className="mental-practice"><header className="practice-heading"><div><p className="eyebrow">Sans piano · {longRun?'Long Run':'Série '+mode}</p><h2>Practice · Mémorisation rapide</h2><p>{longRun?'Trois vies pour aller le plus loin possible. La cadence accélère toutes les 30 secondes.':mode==='passif'?'Pensez à la note, puis laissez sa solution apparaître automatiquement.':'Identifiez la note et sélectionnez votre réponse avant la révélation.'}</p></div>{longRun?<div className="long-stats"><b>{score} pts</b><span>{'♥'.repeat(vies)}{'♡'.repeat(3-vies)}</span><small>Record {record}</small></div>:<span>{compteur} notes vues</span>}</header><CorrespondanceCouleurs/>
  <nav className="practice-type"><button className={!longRun?'active':''} disabled={actif} onClick={()=>changerExperience('serie')}>Série</button><button className={longRun?'active':''} disabled={actif} onClick={()=>changerExperience('long')}>Long Run</button></nav>
  <div className="practice-layout"><div className="practice-card"><div className="practice-game"><Carte midi={midi} reveler={reveler} afficherDiese annonce={annonceNiveau} jauge={actif?{duree:longRun?delaiCourant:delai,cle:compteur}:null}/>{interactif&&<div className="note-buttons">{naturelles.map(n=><button key={n} disabled={!actif||reveler||(longRun&&!!reponse)} className={reveler?(n===noms[midi%12].replace('♯','')?'correct':n===reponse?'wrong':''):n===reponse?'selected':''} onClick={()=>choisir(n)}>{n}</button>)}</div>}</div><div className="practice-actions"><small className={'practice-feedback '+(interactif&&reveler?'visible '+(juste?'answer-good':'answer-bad'):'')} aria-live="polite">{interactif&&reveler?(juste?'Bien vu !':reponse?'Il fallait choisir '+noms[midi%12].replace('♯',''):'Temps écoulé'):' '}</small><button onClick={actif?()=>setActif(false):demarrer}>{actif?'Arrêter':partieFinie?'Rejouer':'Démarrer'}</button><small aria-live="polite">{partieFinie?'Partie terminée · '+score+' points':actif?(reveler?'Solution affichée':'Réponse après '+(longRun?delaiCourant:delai).toFixed(1)+' s'):longRun?'3 vies · départ à 3,0 s':'Prêt pour une nouvelle série'}</small></div></div>
   <aside className="practice-settings"><h3>{longRun?'Long Run':'Réglages'}</h3>{longRun?<div className="long-rules"><div className="level-panel"><b>{niveau===15?'NIVEAU MAX':'NIVEAU '+niveau}</b><strong>{delaiCourant.toFixed(1)} s</strong></div><strong>Score : {score}</strong><span>Vies : {'♥'.repeat(vies)}{'♡'.repeat(3-vies)}</span><span>Record : {record}</span><small>Le délai diminue de 0,2 s toutes les 30 secondes, jusqu’à 0,2 s. Une erreur ou un temps écoulé coûte une vie.</small></div>:<><div className="practice-mode"><button className={mode==='actif'?'setting-on':''} disabled={actif} onClick={()=>setMode('actif')}>Actif</button><button className={mode==='passif'?'setting-on':''} disabled={actif} onClick={()=>setMode('passif')}>Passif</button></div><label>Temps de réflexion <b>{delai.toFixed(1)} s</b><input type="range" min=".8" max="5" step=".2" value={delai} onChange={e=>setDelai(Number(e.target.value))}/></label><label>Durée<select value={duree} onChange={e=>setDuree(Number(e.target.value))}><option value="10">10 secondes</option><option value="30">30 secondes</option><option value="60">1 minute</option><option value="180">3 minutes</option></select></label><button className={chromatique?'setting-on':''} onClick={()=>setChromatique(v=>!v)}>{chromatique?'Avec les dièses':'Notes naturelles seulement'}</button></>}
   </aside></div></section>
}
