import { useEffect, useMemo, useRef, useState } from 'react'
import { savePracticeAttempt, type PracticeResult } from '../storage/progression'

const noms=['Do','Do♯','Ré','Ré♯','Mi','Fa','Fa♯','Sol','Sol♯','La','La♯','Si']
const naturelles=['Do','Ré','Mi','Fa','Sol','La','Si']
const couleurs=['#ef4b4b','#ef4b4b','#f28c28','#f28c28','#f4d43d','#70d35b','#70d35b','#35cbbb','#35cbbb','#6876e8','#6876e8','#d94fc3']
const noires=new Set([1,3,6,8,10]), alea=<T,>(liste:T[])=>liste[Math.floor(Math.random()*liste.length)]
type Experience='serie'|'long'|'chrono'
type Taille=1|3|5
const nomNote=(m:number)=>noms[m%12].replace('♯','')
const signature=(groupe:number[])=>groupe.map(nomNote).sort().join('|')

function CorrespondanceCouleurs(){const naturellesMidi=[60,62,64,65,67,69,71];return <details className="color-reference"><summary>Repère couleurs ↔ notes</summary><div>{naturellesMidi.map(m=><span key={m}><i style={{background:couleurs[m%12]}}/><b>{noms[m%12]}</b></span>)}</div><small>Une croix sur le carré indique un dièse.</small></details>}

function Cartes({groupe,reveler,jauge,annonce}:{groupe:number[];reveler:boolean;jauge?:{duree:number;cle:number}|null;annonce?:number|null}){
 return <div className="flash-stage"><div className="flash-visual"><div className="flash-notes">{groupe.map((m,i)=><div className="flash-note" key={m+'-'+i} style={{background:couleurs[m%12]}}>{noires.has(m%12)&&<b>×</b>}</div>)}</div>{jauge!==undefined&&<div className="time-gauge" aria-hidden="true">{jauge&&!annonce&&<i key={jauge.cle} style={{animationDuration:jauge.duree+'s'}}/>}</div>}</div><div className="flash-answer group-answer">{annonce?<div className="level-inline">⚡ {annonce===15?'MAX':'N'+annonce}</div>:<strong className={reveler?'visible':''}>{groupe.map(m=>noms[m%12].replace('♯','#')).join(' · ')}</strong>}</div></div>
}

export function Practice(){
 const [experience,setExperience]=useState<Experience>('serie'),[taille,setTaille]=useState<Taille>(1),[mode,setMode]=useState<'actif'|'passif'>('actif'),[actif,setActif]=useState(false),[reveler,setReveler]=useState(false),[groupe,setGroupe]=useState<number[]>([60]),[selection,setSelection]=useState<string[]>([]),[valide,setValide]=useState(false),[compteur,setCompteur]=useState(0)
 const [delai,setDelai]=useState(2),[duree,setDuree]=useState(60),[dureeChrono,setDureeChrono]=useState(60),[tempsRestant,setTempsRestant]=useState(60),[chromatique,setChromatique]=useState(true),[score,setScore]=useState(0),[vies,setVies]=useState(3),[record,setRecord]=useState(()=>Number(localStorage.getItem('practice-long-run-record-1')||localStorage.getItem('practice-long-run-record')||0)),[recordChrono,setRecordChrono]=useState(()=>Number(localStorage.getItem('practice-chrono-record-1-60')||localStorage.getItem('practice-chrono-record-60')||0)),[delaiCourant,setDelaiCourant]=useState(3),[niveau,setNiveau]=useState(1),[annonceNiveau,setAnnonceNiveau]=useState<number|null>(null),[verdict,setVerdict]=useState<{juste:boolean;cle:number}|null>(null),[partieFinie,setPartieFinie]=useState(false)
 const fin=useRef(0),debut=useRef(0),precedente=useRef<string|null>(null),reponseRef=useRef(''),viesRef=useRef(3),scoreRef=useRef(0),niveauRef=useRef(1),bonnesRef=useRef(0),questionsRef=useRef(0),tentativeSauvee=useRef(false)
 const longRun=experience==='long',chrono=experience==='chrono',competitif=longRun||chrono
 const notes=useMemo(()=>Array.from({length:12},(_,i)=>60+i).filter(m=>competitif||chromatique||!noires.has(m%12)),[chromatique,competitif])
 const delaiBase=taille===1?3:taille===3?6:10
 const cleRecord=(type:'long'|'chrono',d=dureeChrono)=>type==='long'?`practice-long-run-record-${taille}`:`practice-chrono-record-${taille}-${d}`
 function tirerGroupe(){const disponibles=[...notes],resultat:number[]=[];while(resultat.length<taille&&disponibles.length){const note=alea(disponibles.filter(n=>!resultat.some(r=>nomNote(r)===nomNote(n)))),nom=nomNote(note);resultat.push(note);for(let i=disponibles.length-1;i>=0;i--)if(nomNote(disponibles[i])===nom)disponibles.splice(i,1)}return resultat.sort((a,b)=>a-b)}
 function nouvelleQuestion(){let suivante=tirerGroupe();for(let i=0;i<5&&signature(suivante)===precedente.current;i++)suivante=tirerGroupe();precedente.current=signature(suivante);reponseRef.current='';setGroupe(suivante);setSelection([]);setValide(false);setReveler(false);setCompteur(c=>c+1)}
 function estJuste(g=groupe){return reponseRef.current===signature(g)}
 function enregistrerPoint(type:'long'|'chrono'){scoreRef.current++;setScore(scoreRef.current);const cle=cleRecord(type),ancien=type==='long'?record:recordChrono;if(scoreRef.current>ancien){if(type==='long')setRecord(scoreRef.current);else setRecordChrono(scoreRef.current);localStorage.setItem(cle,String(scoreRef.current))}}
 function perdreVie(){viesRef.current--;setVies(viesRef.current);return viesRef.current===0}
 function terminer(resultat:PracticeResult){if(tentativeSauvee.current||!debut.current)return;tentativeSauvee.current=true;const total=questionsRef.current,bonnes=bonnesRef.current;void savePracticeAttempt({id:crypto.randomUUID(),playedAt:new Date().toISOString(),experience,noteCount:taille,score:experience==='serie'?bonnes:scoreRef.current,correctAnswers:bonnes,totalQuestions:total,accuracy:total?bonnes/total:0,durationSeconds:Math.max(0,Math.round((Date.now()-debut.current)/1000)),configuredDuration:longRun?null:chrono?dureeChrono:duree,reflectionDelay:chrono?null:delai,levelReached:longRun?niveauRef.current:null,result:resultat})}

 useEffect(()=>{if(!actif||chrono)return;let a=0,b=0;const lancer=()=>{if(!longRun&&Date.now()>=fin.current){terminer('completed');setActif(false);setReveler(false);setPartieFinie(true);return}const palier=longRun?Math.min(14,Math.floor((Date.now()-debut.current)/30000)):0,nouveauNiveau=palier+1,attente=longRun?Math.max(taille===1?.2:taille===3?1.5:2.5,delaiBase-palier*(taille===1?.2:.4)):delai;if(longRun&&nouveauNiveau!==niveauRef.current){niveauRef.current=nouveauNiveau;setNiveau(nouveauNiveau);setDelaiCourant(attente);setAnnonceNiveau(nouveauNiveau);b=window.setTimeout(()=>{setAnnonceNiveau(null);lancer()},1200);return}const suivante=tirerGroupe();precedente.current=signature(suivante);reponseRef.current='';setGroupe(suivante);setSelection([]);setValide(false);setDelaiCourant(attente);setReveler(false);setCompteur(c=>c+1);a=window.setTimeout(()=>{setReveler(true);const bonne=estJuste(suivante);questionsRef.current++;if(bonne){bonnesRef.current++;if(!longRun)setScore(bonnesRef.current)}if(longRun){if(bonne)enregistrerPoint('long');else if(perdreVie()){b=window.setTimeout(()=>{terminer('completed');setActif(false);setPartieFinie(true)},650);return}}b=window.setTimeout(lancer,taille===1?700:1000)},attente*1000)};lancer();return()=>{clearTimeout(a);clearTimeout(b)}},[actif,chrono,longRun,notes,taille,delai,delaiBase])
 useEffect(()=>{if(!actif||!chrono)return;const actualiser=()=>{const restant=Math.max(0,Math.ceil((fin.current-Date.now())/1000));setTempsRestant(restant);if(!restant){terminer('completed');setActif(false);setPartieFinie(true)}};actualiser();const id=window.setInterval(actualiser,200);return()=>clearInterval(id)},[actif,chrono])

 function demarrer(){precedente.current=null;reponseRef.current='';debut.current=Date.now();bonnesRef.current=0;questionsRef.current=0;tentativeSauvee.current=false;scoreRef.current=0;setScore(0);setCompteur(0);setSelection([]);setValide(false);setReveler(false);setVerdict(null);setPartieFinie(false);if(competitif){viesRef.current=chrono?1:3;setVies(chrono?1:3);setDelaiCourant(delaiBase);setNiveau(1);niveauRef.current=0;setAnnonceNiveau(null)}if(chrono){fin.current=Date.now()+dureeChrono*1000;setTempsRestant(dureeChrono);nouvelleQuestion()}else if(!longRun)fin.current=Date.now()+duree*1000;setActif(true)}
 function basculerNote(n:string){if(!actif||reveler||valide)return;const prochaine=selection.includes(n)?selection.filter(x=>x!==n):selection.length<taille?[...selection,n]:selection;setSelection(prochaine);reponseRef.current=[...prochaine].sort().join('|');if(prochaine.length===taille)valider(prochaine)}
 function valider(sel=selection){if(sel.length!==taille)return;reponseRef.current=[...sel].sort().join('|');setValide(true);if(chrono){const bonne=reponseRef.current===signature(groupe);questionsRef.current++;if(bonne){bonnesRef.current++;setVerdict({juste:true,cle:Date.now()});enregistrerPoint('chrono');nouvelleQuestion()}else{setVerdict({juste:false,cle:Date.now()});perdreVie();terminer('disqualified');setActif(false);setPartieFinie(true)}}}
 function arreter(){terminer('stopped');setActif(false)}
 function changerTaille(t:Taille){setTaille(t);setDelai(t===1?2:t===3?5:8);setGroupe(Array.from({length:t},(_,i)=>[60,62,64,65,67][i]));setSelection([]);setRecord(Number(localStorage.getItem(`practice-long-run-record-${t}`)||0));setRecordChrono(Number(localStorage.getItem(`practice-chrono-record-${t}-${dureeChrono}`)||0))}
 function changerExperience(e:Experience){setExperience(e);setPartieFinie(false);setReveler(false);setSelection([]);setAnnonceNiveau(null);if(e==='long')setRecord(Number(localStorage.getItem(cleRecord('long'))||0));if(e==='chrono')setRecordChrono(Number(localStorage.getItem(cleRecord('chrono'))||0))}
 function changerDureeChrono(d:number){setDureeChrono(d);setTempsRestant(d);setRecordChrono(Number(localStorage.getItem(cleRecord('chrono',d))||0))}
 const juste=reponseRef.current===signature(groupe),temps=Math.floor(tempsRestant/60)+':'+String(tempsRestant%60).padStart(2,'0'),interactif=competitif||mode==='actif'

 return <section className="mental-practice"><header className="practice-heading"><div><p className="eyebrow">Sans piano · {taille===1?'Une note':taille+' notes'} · {longRun?'Long Run':chrono?'Contre-la-montre':'Série '+mode}</p><h2>Practice · Mémorisation rapide</h2><p>{longRun?'Trois vies pour aller le plus loin possible. La cadence accélère toutes les 30 secondes.':chrono?'Une seule erreur vous disqualifie : trouvez le plus de groupes possible.':mode==='passif'?'Mémorisez le groupe, puis laissez sa solution apparaître.':'Sélectionnez toutes les notes du groupe avant la révélation.'}</p></div>{competitif?<div className="long-stats"><b>{score} pts</b>{longRun&&<span>{'♥'.repeat(vies)}{'♡'.repeat(3-vies)}</span>}<small>{chrono&&actif?temps+' · ':''}Record {chrono?recordChrono:record}</small></div>:<span>{compteur} groupes vus</span>}</header><CorrespondanceCouleurs/>
  <nav className="practice-size" aria-label="Nombre de notes">{([1,3,5] as Taille[]).map(t=><button key={t} className={taille===t?'active':''} disabled={actif} onClick={()=>changerTaille(t)}>{t===1?'1 note':t+' notes'}</button>)}</nav>
  <nav className="practice-type"><button className={experience==='serie'?'active':''} disabled={actif} onClick={()=>changerExperience('serie')}>Série</button><button className={longRun?'active':''} disabled={actif} onClick={()=>changerExperience('long')}>Long Run</button><button className={chrono?'active':''} disabled={actif} onClick={()=>changerExperience('chrono')}>Contre-la-montre</button></nav>
  <div className="practice-layout"><div className="practice-card">{chrono&&verdict&&<span key={verdict.cle} className={'chrono-verdict '+(verdict.juste?'good':'bad')}>{verdict.juste?'✓':'×'}</span>}<div className={'practice-game '+(taille>1?'group-mode':'')}><Cartes groupe={groupe} reveler={reveler} annonce={annonceNiveau} jauge={chrono?undefined:actif?{duree:longRun?delaiCourant:delai,cle:compteur}:null}/>{interactif&&<div className="note-buttons">{naturelles.map(n=><button key={n} disabled={!actif||reveler||valide} className={reveler?(groupe.map(nomNote).includes(n)?'correct':selection.includes(n)?'wrong':''):selection.includes(n)?'selected':''} onClick={()=>basculerNote(n)}>{n}</button>)}</div>}</div><div className="practice-actions"><small className={'practice-feedback '+(interactif&&reveler?'visible '+(juste?'answer-good':'answer-bad'):'')}>{interactif&&reveler?(juste?'Bien vu !':'Réponse : '+groupe.map(m=>noms[m%12]).join(', ')):' '}</small><button onClick={actif?arreter:demarrer}>{actif?'Arrêter':partieFinie?'Rejouer':'Démarrer'}</button><small>{partieFinie?(chrono&&vies===0?'Disqualifié · ':'Partie terminée · ')+score+' points':actif?(chrono?'À vous de jouer · '+temps:'Réponse après '+(longRun?delaiCourant:delai).toFixed(1)+' s'):longRun?'3 vies · départ à '+delaiBase.toFixed(1)+' s':chrono?'Zéro erreur · '+dureeChrono/60+' min':'Prêt pour une nouvelle série'}</small></div></div>
   <aside className="practice-settings"><h3>{longRun?'Long Run':chrono?'Contre-la-montre':'Réglages'}</h3>{longRun?<div className="long-rules"><div className="level-panel"><b>{niveau===15?'NIVEAU MAX':'NIVEAU '+niveau}</b><strong>{delaiCourant.toFixed(1)} s</strong></div><strong>Score : {score}</strong><span>Vies : {'♥'.repeat(vies)}{'♡'.repeat(3-vies)}</span><span>Record ({taille} note{taille>1?'s':''}) : {record}</span><small>Un groupe entièrement juste rapporte un point. Une erreur ou une réponse incomplète coûte une vie.</small></div>:chrono?<div className="long-rules"><div className="level-panel"><b>TEMPS RESTANT</b><strong>{temps}</strong></div><strong>Score : {score}</strong><span>{partieFinie&&vies===0?'Disqualifié':'Zéro erreur autorisée'}</span><span>Record ({taille} note{taille>1?'s':''} · {dureeChrono/60} min) : {recordChrono}</span><label>Durée<select disabled={actif} value={dureeChrono} onChange={e=>changerDureeChrono(Number(e.target.value))}><option value="60">1 minute</option><option value="180">3 minutes</option><option value="300">5 minutes</option></select></label><small>La dernière note sélectionnée valide automatiquement le groupe. La première erreur met fin à la partie.</small></div>:<><div className="practice-mode"><button className={mode==='actif'?'setting-on':''} disabled={actif} onClick={()=>setMode('actif')}>Actif</button><button className={mode==='passif'?'setting-on':''} disabled={actif} onClick={()=>setMode('passif')}>Passif</button></div><label>Temps de réflexion <b>{delai.toFixed(1)} s</b><input type="range" min={taille===1?.8:taille===3?2:3} max={taille===1?5:taille===3?10:15} step=".5" value={delai} onChange={e=>setDelai(Number(e.target.value))}/></label><label>Durée<select value={duree} onChange={e=>setDuree(Number(e.target.value))}><option value="30">30 secondes</option><option value="60">1 minute</option><option value="180">3 minutes</option></select></label><button className={chromatique?'setting-on':''} onClick={()=>setChromatique(v=>!v)}>{chromatique?'Avec les dièses':'Notes naturelles seulement'}</button></>}
   </aside></div></section>
}
