import { useEffect, useMemo, useRef, useState } from 'react'
import { createAttemptId, getLongRunUnlockProgress, listPracticeAttempts, LONG_RUN_MAX_LEVEL, type LongRunUnlockProgress, savePracticeAttempt, type PracticeResult } from '../storage/progression'

const noms=['Do','Do♯','Ré','Ré♯','Mi','Fa','Fa♯','Sol','Sol♯','La','La♯','Si']
const naturelles=['Do','Ré','Mi','Fa','Sol','La','Si']
const couleurs=['#ef4b4b','#ef4b4b','#f28c28','#f28c28','#f4d43d','#70d35b','#70d35b','#35cbbb','#35cbbb','#6876e8','#6876e8','#d94fc3']
const noires=new Set([1,3,6,8,10]), alea=<T,>(liste:T[])=>liste[Math.floor(Math.random()*liste.length)]
const melanger=<T,>(liste:T[])=>{const resultat=[...liste];for(let i=resultat.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[resultat[i],resultat[j]]=[resultat[j],resultat[i]]}return resultat}
type Experience='long'|'chrono'
type Taille=1|3|5
const DUREE_NIVEAU_LONG_RUN=30_000, NIVEAU_MAX=LONG_RUN_MAX_LEVEL
const nomNote=(m:number)=>noms[m%12].replace('♯','')
const signature=(groupe:number[])=>groupe.map(nomNote).sort().join('|')
const delaiDuNiveau=(taille:Taille,niveau:number)=>Math.max(taille===1?.2:taille===3?1.5:2.5,(taille===1?3:taille===3?6:10)-(niveau-1)*(taille===1?.2:.4))
const pointsAcquisAvantNiveau=(taille:Taille,niveau:number)=>Array.from({length:niveau-1},(_,index)=>Math.floor(DUREE_NIVEAU_LONG_RUN/1000/delaiDuNiveau(taille,index+1)+1e-9)).reduce((total,points)=>total+points,0)
function CorrespondanceCouleurs(){const naturellesMidi=[60,62,64,65,67,69,71];return <details className="color-reference"><summary>Repère couleurs ↔ notes</summary><div>{naturellesMidi.map(m=><span key={m}><i style={{background:couleurs[m%12]}}/><b>{noms[m%12]}</b></span>)}</div><small>Une croix sur le carré indique un dièse.</small></details>}

function Cartes({groupe,reveler,jauge,annonce}:{groupe:number[];reveler:boolean;jauge?:{duree:number;cle:number}|null;annonce?:number|null}){
 return <div className="flash-stage"><div className="flash-visual"><div className="flash-notes">{groupe.map((m,i)=><div className="flash-note" key={m+'-'+i} style={{background:couleurs[m%12]}}>{noires.has(m%12)&&<b>×</b>}</div>)}</div>{jauge!==undefined&&<div className="time-gauge" aria-hidden="true">{jauge&&!annonce&&<i key={jauge.cle} style={{animationDuration:jauge.duree+'s'}}/>}</div>}</div><div className="flash-answer group-answer">{annonce?<div className="level-inline">⚡ {annonce===15?'MAX':'N'+annonce}</div>:<strong className={reveler?'visible':''}>{groupe.map(m=>noms[m%12].replace('♯','#')).join(' · ')}</strong>}</div></div>
}

export function Practice(){
 const [experience,setExperience]=useState<Experience>('long'),[taille,setTaille]=useState<Taille>(1),[actif,setActif]=useState(false),[reveler,setReveler]=useState(false),[groupe,setGroupe]=useState<number[]>([60]),[selection,setSelection]=useState<string[]>([]),[valide,setValide]=useState(false),[compteur,setCompteur]=useState(0)
 const [delai,setDelai]=useState(2),[duree,setDuree]=useState(60),[dureeChrono,setDureeChrono]=useState(60),[tempsRestant,setTempsRestant]=useState(60),[score,setScore]=useState(0),[vies,setVies]=useState(3),[record,setRecord]=useState(0),[recordChrono,setRecordChrono]=useState(0),[recordChronoDepart,setRecordChronoDepart]=useState(0),[delaiCourant,setDelaiCourant]=useState(3),[niveau,setNiveau]=useState(1),[niveauDepart,setNiveauDepart]=useState(1),[progressionNiveau,setProgressionNiveau]=useState<LongRunUnlockProgress>(()=>getLongRunUnlockProgress([],1)),[annonceNiveau,setAnnonceNiveau]=useState<number|null>(null),[verdict,setVerdict]=useState<{juste:boolean;cle:number}|null>(null),[partieFinie,setPartieFinie]=useState(false)
 const fin=useRef(0),debut=useRef(0),precedente=useRef<string|null>(null),reponseRef=useRef(''),viesRef=useRef(3),scoreRef=useRef(0),niveauRef=useRef(1),niveauDepartRef=useRef(1),bonnesRef=useRef(0),questionsRef=useRef(0),tentativeSauvee=useRef(false),niveauxAvecFauteRef=useRef(new Set<number>()),niveauxParfaitsRef=useRef<number[]>([])
 const longRun=experience==='long',chrono=experience==='chrono',competitif=longRun||chrono
 const notes=useMemo(()=>Array.from({length:12},(_,i)=>60+i),[])
 const delaiBase=taille===1?3:taille===3?6:10
 function tirerGroupe(){const groupes:number[][]=[];const ajouter=(depart:number,choix:number[])=>{if(choix.length===taille){if(signature(choix)!==precedente.current)groupes.push(choix);return}for(let i=depart;i<notes.length;i++)if(!choix.some(n=>nomNote(n)===nomNote(notes[i])))ajouter(i+1,[...choix,notes[i]])};ajouter(0,[]);return melanger(alea(groupes))}
 function nouvelleQuestion(){const suivante=tirerGroupe();precedente.current=signature(suivante);reponseRef.current='';setGroupe(suivante);setSelection([]);setValide(false);setReveler(false);setCompteur(c=>c+1)}
 function estJuste(g=groupe){return reponseRef.current===signature(g)}
 function enregistrerPoint(_type:'long'|'chrono'){scoreRef.current++;setScore(scoreRef.current)}
 function perdreVie(){viesRef.current--;setVies(viesRef.current);return viesRef.current===0}
 function terminer(resultat:PracticeResult){if(tentativeSauvee.current||!debut.current)return;tentativeSauvee.current=true;const total=questionsRef.current,bonnes=bonnesRef.current;void savePracticeAttempt({id:createAttemptId(),playedAt:new Date().toISOString(),experience,noteCount:taille,score:scoreRef.current,correctAnswers:bonnes,totalQuestions:total,accuracy:total?bonnes/total:0,durationSeconds:Math.max(0,Math.round((Date.now()-debut.current)/1000)),configuredDuration:chrono?dureeChrono:null,reflectionDelay:null,levelReached:longRun?niveauRef.current:null,perfectLevels:longRun?[...niveauxParfaitsRef.current]:undefined,result:resultat}).then(async()=>{if(resultat!=='stopped'){if(experience==='long')setRecord(current=>Math.max(current,scoreRef.current));else setRecordChrono(current=>Math.max(current,scoreRef.current))}const attempts=await listPracticeAttempts(),progression=getLongRunUnlockProgress(attempts,taille);setNiveauDepart(progression.unlockedLevel);setProgressionNiveau(progression)}).catch(error=>console.error('Impossible d’enregistrer la partie',error))}

 useEffect(()=>{if(!actif||chrono)return;let a=0,b=0;const lancer=()=>{if(!longRun&&Date.now()>=fin.current){terminer('completed');setActif(false);setReveler(false);setPartieFinie(true);return}const palier=longRun?Math.min(NIVEAU_MAX-1,niveauDepartRef.current-1+Math.floor((Date.now()-debut.current)/DUREE_NIVEAU_LONG_RUN)):0,nouveauNiveau=palier+1,attente=longRun?delaiDuNiveau(taille,nouveauNiveau):delai;if(longRun&&nouveauNiveau!==niveauRef.current){const niveauTermine=niveauRef.current;if(!niveauxAvecFauteRef.current.has(niveauTermine))niveauxParfaitsRef.current.push(niveauTermine);niveauRef.current=nouveauNiveau;setNiveau(nouveauNiveau);setDelaiCourant(attente);setAnnonceNiveau(nouveauNiveau);b=window.setTimeout(()=>{setAnnonceNiveau(null);lancer()},1200);return}const suivante=tirerGroupe();precedente.current=signature(suivante);reponseRef.current='';setGroupe(suivante);setSelection([]);setValide(false);setDelaiCourant(attente);setReveler(false);setCompteur(c=>c+1);a=window.setTimeout(()=>{setReveler(true);const bonne=estJuste(suivante);questionsRef.current++;if(bonne){bonnesRef.current++;if(!longRun)setScore(bonnesRef.current)}if(longRun){if(bonne)enregistrerPoint('long');else{niveauxAvecFauteRef.current.add(niveauRef.current);if(perdreVie()){b=window.setTimeout(()=>{terminer('completed');setActif(false);setPartieFinie(true)},650);return}}}b=window.setTimeout(lancer,taille===1?700:1000)},attente*1000)};lancer();return()=>{clearTimeout(a);clearTimeout(b)}},[actif,chrono,longRun,notes,taille,delaiBase])
 useEffect(()=>{let cancelled=false;listPracticeAttempts().then(attempts=>{if(cancelled)return;const completed=attempts.filter(t=>t.noteCount===taille&&t.result!=='stopped'),progression=getLongRunUnlockProgress(attempts,taille);setRecord(Math.max(0,...completed.filter(t=>t.experience==='long').map(t=>t.score)));setRecordChrono(Math.max(0,...completed.filter(t=>t.experience==='chrono'&&t.configuredDuration===dureeChrono).map(t=>t.score)));setNiveauDepart(progression.unlockedLevel);setProgressionNiveau(progression)}).catch(error=>console.error('Impossible de charger les records',error));return()=>{cancelled=true}},[taille,dureeChrono])
 useEffect(()=>{if(!actif&&!partieFinie&&longRun){setNiveau(niveauDepart);setDelaiCourant(delaiDuNiveau(taille,niveauDepart))}},[actif,partieFinie,longRun,niveauDepart,taille])
 useEffect(()=>{if(!actif||!chrono)return;const actualiser=()=>{const restant=Math.max(0,Math.ceil((fin.current-Date.now())/1000));setTempsRestant(restant);if(!restant){terminer('completed');setActif(false);setPartieFinie(true)}};actualiser();const id=window.setInterval(actualiser,200);return()=>clearInterval(id)},[actif,chrono])

 function demarrer(){const niveauInitial=longRun?niveauDepart:1,scoreInitial=longRun?pointsAcquisAvantNiveau(taille,niveauInitial):0;precedente.current=null;reponseRef.current='';debut.current=Date.now();bonnesRef.current=0;questionsRef.current=0;tentativeSauvee.current=false;niveauxAvecFauteRef.current=new Set();niveauxParfaitsRef.current=[];scoreRef.current=scoreInitial;setScore(scoreInitial);setRecordChronoDepart(recordChrono);setCompteur(0);setSelection([]);setValide(false);setReveler(false);setVerdict(null);setPartieFinie(false);if(competitif){viesRef.current=chrono?1:3;setVies(chrono?1:3);niveauDepartRef.current=niveauInitial;setDelaiCourant(delaiDuNiveau(taille,niveauInitial));setNiveau(niveauInitial);niveauRef.current=niveauInitial;setAnnonceNiveau(null)}if(chrono){fin.current=Date.now()+dureeChrono*1000;setTempsRestant(dureeChrono);nouvelleQuestion()}else if(!longRun)fin.current=Date.now()+duree*1000;setActif(true)}
 function basculerNote(n:string){if(!actif||reveler||valide)return;const prochaine=selection.includes(n)?selection.filter(x=>x!==n):selection.length<taille?[...selection,n]:selection;setSelection(prochaine);reponseRef.current=[...prochaine].sort().join('|');if(prochaine.length===taille)valider(prochaine)}
 function valider(sel=selection){if(sel.length!==taille)return;reponseRef.current=[...sel].sort().join('|');setValide(true);if(chrono){const bonne=reponseRef.current===signature(groupe);questionsRef.current++;if(bonne){bonnesRef.current++;setVerdict({juste:true,cle:Date.now()});enregistrerPoint('chrono');nouvelleQuestion()}else{setVerdict({juste:false,cle:Date.now()});perdreVie();terminer('disqualified');setActif(false);setPartieFinie(true)}}}
 function arreter(){terminer('stopped');setActif(false)}
 function changerTaille(t:Taille){setTaille(t);setGroupe(melanger(Array.from({length:t},(_,i)=>[60,62,64,65,67][i])));setSelection([]);setPartieFinie(false)}
 function changerExperience(e:Experience){setExperience(e);setPartieFinie(false);setReveler(false);setSelection([]);setAnnonceNiveau(null)}
 function changerDureeChrono(d:number){setDureeChrono(d);setTempsRestant(d)}
 const juste=reponseRef.current===signature(groupe),temps=Math.floor(tempsRestant/60)+':'+String(tempsRestant%60).padStart(2,'0'),interactif=true,objectifChrono=(actif||partieFinie?recordChronoDepart:recordChrono)+1
 const retourChrono=score>recordChronoDepart?'Nouveau record · +'+(score-recordChronoDepart):recordChronoDepart>0&&score===recordChronoDepart?'Record égalé · encore 1 groupe pour le battre':(objectifChrono-score)+' groupe'+(objectifChrono-score>1?'s':'')+' avant le prochain record'

 return <section className={'mental-practice '+(longRun?'long-run':'chrono-run')}><header className="practice-heading"><div><p className="eyebrow">Sans piano · {taille===1?'Une note':taille+' notes'} · {longRun?'Long Run':'Contre-la-montre'}</p><h2>Practice · Mémorisation rapide</h2><p>{longRun?'Trois vies pour aller le plus loin possible. La cadence accélère toutes les 30 secondes.':'Une seule erreur vous disqualifie : trouvez le plus de groupes possible.'}</p></div><div className="long-stats"><b>{score} pts</b>{longRun&&<span>{'♥'.repeat(vies)}{'♡'.repeat(3-vies)}</span>}<small>{chrono&&actif?temps+' · ':''}Record {chrono?recordChrono:record}</small></div></header><CorrespondanceCouleurs/>
  <nav className="practice-size" aria-label="Nombre de notes">{([1,3,5] as Taille[]).map(t=><button key={t} className={taille===t?'active':''} disabled={actif} onClick={()=>changerTaille(t)}>{t===1?'1 note':t+' notes'}</button>)}</nav>
  <nav className="practice-type"><button className={longRun?'active':''} disabled={actif} onClick={()=>changerExperience('long')}>Long Run</button><button className={chrono?'active':''} disabled={actif} onClick={()=>changerExperience('chrono')}>Contre-la-montre</button></nav>
  <div className="practice-layout"><div className="practice-card">{chrono&&verdict&&<span key={verdict.cle} className={'chrono-verdict '+(verdict.juste?'good':'bad')}>{verdict.juste?'✓':'×'}</span>}<div className={'practice-game '+(taille>1?'group-mode':'')}>{longRun&&<div className="mobile-long-stats" aria-label={'Score '+score+', niveau '+niveau+', '+vies+' vies restantes, record '+record}><span><small>Score</small><strong>{score}</strong></span><span><small>Niveau</small><strong>N{niveau}</strong></span><span><small>Vies</small><strong className="mobile-lives">{'♥'.repeat(vies)}{'♡'.repeat(3-vies)}</strong></span><span><small>Record</small><strong>{record}</strong></span></div>}{chrono&&<div className="mobile-chrono-stats" aria-label={'Score '+score+', record '+recordChrono}><span><small>Score</small><strong>{score}</strong></span><span><small>Record</small><strong>{recordChrono}</strong></span></div>}<Cartes groupe={groupe} reveler={reveler} annonce={annonceNiveau} jauge={chrono?undefined:actif?{duree:longRun?delaiCourant:delai,cle:compteur}:null}/>{interactif&&<div className="note-buttons">{naturelles.map(n=><button key={n} disabled={!actif||reveler||valide} className={reveler?(groupe.map(nomNote).includes(n)?'correct':selection.includes(n)?'wrong':''):selection.includes(n)?'selected':''} onClick={()=>basculerNote(n)}>{n}</button>)}</div>}</div><div className="practice-actions"><small className={'practice-feedback '+(interactif&&reveler?'visible '+(juste?'answer-good':'answer-bad'):'')}>{interactif&&reveler?(juste?'Bien vu !':'Réponse : '+groupe.map(m=>noms[m%12]).join(', ')):' '}</small><button onClick={actif?arreter:demarrer}>{actif?'Arrêter':partieFinie?'Rejouer':'Démarrer'}</button><small>{partieFinie?(chrono&&vies===0?'Disqualifié · ':'Partie terminée · ')+score+' points':actif?(chrono?'À vous de jouer · '+temps:'Réponse après '+(longRun?delaiCourant:delai).toFixed(1)+' s'):longRun?'Départ N'+niveauDepart+' à '+delaiDuNiveau(taille,niveauDepart).toFixed(1)+' s'+(niveauDepart>1?' · '+pointsAcquisAvantNiveau(taille,niveauDepart)+' pts acquis':''):'Zéro erreur · '+dureeChrono/60+' min'}</small></div></div>
   <aside className="practice-settings"><h3>{longRun?'Long Run':'Contre-la-montre'}</h3>{longRun?<div className="long-rules"><div className="unlock-card"><header><span>Niveau débloqué</span><strong>N{progressionNiveau.unlockedLevel}</strong></header>{progressionNiveau.isMaxLevel?<p>🏆 Tous les niveaux sont débloqués</p>:<><div className="unlock-target"><span>Prochain objectif · réussir N{progressionNiveau.unlockedLevel}</span><b>{progressionNiveau.qualifyingRuns}/{progressionNiveau.runsRequired}</b></div><div className="unlock-progress" role="progressbar" aria-label={'Progression vers le niveau '+(progressionNiveau.unlockedLevel+1)} aria-valuemin={0} aria-valuemax={progressionNiveau.runsRequired} aria-valuenow={progressionNiveau.qualifyingRuns}><i style={{width:(progressionNiveau.qualifyingRuns/progressionNiveau.runsRequired*100)+'%'}}/></div><small>Terminez entièrement N{progressionNiveau.unlockedLevel} sans faute encore {progressionNiveau.runsRemaining} fois pour débloquer N{progressionNiveau.unlockedLevel+1}</small></>}</div><div className="level-panel long-current-level"><b>{niveau===15?'NIVEAU MAX':'NIVEAU EN COURS · '+niveau}</b><strong>{delaiCourant.toFixed(1)} s</strong></div><strong className="long-score">Score : {score}</strong><span className="long-lives">Vies : {'♥'.repeat(vies)}{'♡'.repeat(3-vies)}</span><span className="long-record">Record ({taille} note{taille>1?'s':''}) : {record}</span><small>Un groupe entièrement juste rapporte un point. Une erreur ou une réponse incomplète coûte une vie et invalide ce niveau pour le déblocage.</small></div>:<div className="long-rules"><div className="chrono-goal"><span>PROCHAIN RECORD</span><strong>{objectifChrono} pts</strong><small>{actif||partieFinie?retourChrono:'Une cible juste au-dessus de votre record'}</small></div><div className="level-panel"><b>TEMPS RESTANT</b><strong>{temps}</strong></div><strong className="chrono-score">Score : {score}</strong><span>{partieFinie&&vies===0?'Disqualifié':'Zéro erreur autorisée'}</span><span className="chrono-record">Record ({taille} note{taille>1?'s':''} · {dureeChrono/60} min) : {recordChrono}</span><label>Durée<select disabled={actif} value={dureeChrono} onChange={e=>changerDureeChrono(Number(e.target.value))}><option value="60">1 minute</option><option value="180">3 minutes</option><option value="300">5 minutes</option></select></label><small>La dernière note sélectionnée valide automatiquement le groupe. La première erreur met fin à la partie.</small></div>}</aside></div></section>
}
