import { useEffect, useMemo, useState } from 'react'
import { listPracticeAttempts, type PracticeAttempt, type PracticeExperience } from '../storage/progression'

const libelles: Record<PracticeExperience,string>={serie:'Série',long:'Long Run',chrono:'Contre-la-montre'}

export function Progression(){
 const [tentatives,setTentatives]=useState<PracticeAttempt[]>([]),[experience,setExperience]=useState<PracticeExperience>('chrono'),[taille,setTaille]=useState<1|3|5>(1),[charge,setCharge]=useState(true)
 useEffect(()=>{listPracticeAttempts().then(setTentatives).finally(()=>setCharge(false))},[])
 const filtrees=useMemo(()=>tentatives.filter(t=>t.experience===experience&&t.noteCount===taille&&t.result!=='stopped'),[tentatives,experience,taille])
 const valeurs=filtrees.map(t=>experience==='serie'?Math.round(t.accuracy*100):t.score),maximum=Math.max(1,...valeurs),moyenne=valeurs.length?valeurs.reduce((a,b)=>a+b,0)/valeurs.length:0
 const points=valeurs.map((v,i)=>`${valeurs.length===1?50:5+i*90/(valeurs.length-1)},${92-v/maximum*78}`).join(' ')
 return <section className="progress-page"><header className="training-intro"><div><p className="eyebrow">Historique local</p><h2>Ma progression</h2><p>Chaque point représente une partie enregistrée sur cet appareil.</p></div><strong>{tentatives.length} tentative{tentatives.length!==1?'s':''}</strong></header>
  <div className="progress-filters"><label>Épreuve<select value={experience} onChange={e=>setExperience(e.target.value as PracticeExperience)}>{Object.entries(libelles).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Lecture<select value={taille} onChange={e=>setTaille(Number(e.target.value) as 1|3|5)}><option value="1">1 note</option><option value="3">3 notes</option><option value="5">5 notes</option></select></label></div>
  {charge?<p className="progress-empty">Chargement…</p>:!filtrees.length?<p className="progress-empty">Aucune partie terminée pour cette épreuve. Jouez une partie dans Practice pour commencer la courbe.</p>:<><div className="progress-metrics"><article><span>Tentatives</span><strong>{filtrees.length}</strong></article><article><span>{experience==='serie'?'Meilleure précision':'Record'}</span><strong>{Math.max(...valeurs)}{experience==='serie'?' %':' pts'}</strong></article><article><span>Moyenne</span><strong>{moyenne.toFixed(1)}{experience==='serie'?' %':' pts'}</strong></article></div>
   <section className="progress-chart"><header><div><h3>{experience==='serie'?'Précision':'Score'} par tentative</h3><small>Anciennes → récentes</small></div><b>{libelles[experience]} · {taille} note{taille>1?'s':''}</b></header><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Courbe de progression"><line x1="5" y1="92" x2="95" y2="92"/><line x1="5" y1="14" x2="5" y2="92"/><polyline points={points}/>{valeurs.map((v,i)=><circle key={filtrees[i].id} cx={valeurs.length===1?50:5+i*90/(valeurs.length-1)} cy={92-v/maximum*78} r="1.5"><title>{new Date(filtrees[i].playedAt).toLocaleDateString('fr-FR')} · {v}{experience==='serie'?' %':' pts'}</title></circle>)}</svg></section>
   <div className="attempt-list">{[...filtrees].reverse().slice(0,8).map(t=><article key={t.id}><div><strong>{new Date(t.playedAt).toLocaleDateString('fr-FR',{day:'2-digit',month:'short',year:'numeric'})}</strong><small>{t.result==='disqualified'?'Disqualifié':t.result==='completed'?'Terminé':'Interrompu'} · {t.totalQuestions} question{t.totalQuestions!==1?'s':''}</small></div><b>{experience==='serie'?Math.round(t.accuracy*100)+' %':t.score+' pts'}</b></article>)}</div></>}
 </section>
}
