import { useEffect, useMemo, useState } from 'react'
import { getLongRunUnlockProgress, listPracticeAttempts, type PracticeAttempt, type PracticeExperience } from '../storage/progression'

const libelles: Record<PracticeExperience,string>={long:'Long Run',chrono:'Contre-la-montre'}

export function Progression(){
 const [tentatives,setTentatives]=useState<PracticeAttempt[]>([]),[experience,setExperience]=useState<PracticeExperience>('chrono'),[taille,setTaille]=useState<1|3|5>(1),[dureeChrono,setDureeChrono]=useState(60),[charge,setCharge]=useState(true)
 useEffect(()=>{listPracticeAttempts().then(setTentatives).finally(()=>setCharge(false))},[])
 const filtrees=useMemo(()=>tentatives.filter(t=>t.experience===experience&&t.noteCount===taille&&t.result!=='stopped'&&(experience!=='chrono'||t.configuredDuration===dureeChrono)),[tentatives,experience,taille,dureeChrono])
 const progressionNiveau=useMemo(()=>getLongRunUnlockProgress(tentatives,taille),[tentatives,taille])
 const valeurs=filtrees.map(t=>t.score),maximum=Math.max(1,...valeurs),moyenne=valeurs.length?valeurs.reduce((a,b)=>a+b,0)/valeurs.length:0
 const points=valeurs.map((v,i)=>`${valeurs.length===1?50:5+i*90/(valeurs.length-1)},${92-v/maximum*78}`).join(' ')
 return <section className="progress-page"><header className="training-intro"><div><p className="eyebrow">Historique local</p><h2>Ma progression</h2><p>Chaque point représente une partie enregistrée sur cet appareil.</p></div><strong>{tentatives.length} tentative{tentatives.length!==1?'s':''}</strong></header>
  <div className="progress-filters"><div className="progress-filter-group"><span>Épreuve</span><nav className="progress-filter-options" aria-label="Épreuve">{(['long','chrono'] as PracticeExperience[]).map(value=><button type="button" key={value} className={experience===value?'active':''} aria-pressed={experience===value} onClick={()=>setExperience(value)}>{libelles[value]}</button>)}</nav></div><div className="progress-filter-group"><span>Lecture</span><nav className="progress-filter-options" aria-label="Nombre de notes">{([1,3,5] as const).map(value=><button type="button" key={value} className={taille===value?'active':''} aria-pressed={taille===value} onClick={()=>setTaille(value)}>{value} note{value>1?'s':''}</button>)}</nav></div>{experience==='chrono'&&<div className="progress-filter-group"><span>Durée</span><nav className="progress-filter-options" aria-label="Durée">{([60,180,300] as const).map(value=><button type="button" key={value} className={dureeChrono===value?'active':''} aria-pressed={dureeChrono===value} onClick={()=>setDureeChrono(value)}>{value/60} min</button>)}</nav></div>}</div>
  {experience==='long'&&<section className="progress-unlock"><div className="progress-level-badge"><span>Niveau débloqué</span><strong>N{progressionNiveau.unlockedLevel}</strong><small>{taille} note{taille>1?'s':''}</small></div><div className="progress-unlock-body">{progressionNiveau.isMaxLevel?<><span className="eyebrow">Long Run maîtrisé</span><h3>🏆 Niveau maximum débloqué</h3><p>Vous pouvez désormais démarrer directement au niveau {progressionNiveau.unlockedLevel}.</p></>:<><div className="progress-unlock-copy"><div><span className="eyebrow">Prochain niveau</span><h3>Débloquer le niveau {progressionNiveau.unlockedLevel+1}</h3></div><b>{progressionNiveau.qualifyingRuns} / {progressionNiveau.runsRequired}</b></div><div className="unlock-progress" role="progressbar" aria-label={'Progression vers le niveau '+(progressionNiveau.unlockedLevel+1)} aria-valuemin={0} aria-valuemax={progressionNiveau.runsRequired} aria-valuenow={progressionNiveau.qualifyingRuns}><i style={{width:(progressionNiveau.qualifyingRuns/progressionNiveau.runsRequired*100)+'%'}}/></div><p>Terminez entièrement le niveau {progressionNiveau.unlockedLevel}, sans aucune faute, encore {progressionNiveau.runsRemaining} fois. Il faut 5 réussites parfaites pour débloquer le niveau suivant.</p></>}</div></section>}
  {charge?<p className="progress-empty">Chargement…</p>:!filtrees.length?<p className="progress-empty">Aucune partie terminée pour cette épreuve. Jouez une partie dans Practice pour commencer la courbe.</p>:<><div className="progress-metrics"><article><span>Tentatives</span><strong>{filtrees.length}</strong></article><article><span>Record</span><strong>{Math.max(...valeurs)} pts</strong></article><article><span>Moyenne</span><strong>{moyenne.toFixed(1)} pts</strong></article></div>
   <section className="progress-chart"><header><div><h3>Score par tentative</h3><small>Anciennes → récentes</small></div><b>{libelles[experience]} · {taille} note{taille>1?'s':''}</b></header><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Courbe de progression"><line x1="5" y1="92" x2="95" y2="92"/><line x1="5" y1="14" x2="5" y2="92"/><polyline points={points}/>{valeurs.map((v,i)=><circle key={filtrees[i].id} cx={valeurs.length===1?50:5+i*90/(valeurs.length-1)} cy={92-v/maximum*78} r="1.5"><title>{new Date(filtrees[i].playedAt).toLocaleDateString('fr-FR')} · {v} pts</title></circle>)}</svg></section>
   <div className="attempt-list">{[...filtrees].reverse().slice(0,8).map(t=><article key={t.id}><div><strong>{new Date(t.playedAt).toLocaleDateString('fr-FR',{day:'2-digit',month:'short',year:'numeric'})}</strong><small>{t.result==='disqualified'?'Disqualifié':t.result==='completed'?'Terminé':'Interrompu'} · {t.totalQuestions} question{t.totalQuestions!==1?'s':''}</small></div><b>{t.score+' pts'}</b></article>)}</div></>}
 </section>
}
